#:include common/sprite.kv

#:import choice random.choice
#:import DodgeMob mob.DodgeMob
#:import AnimatedSprite common.sprite.AnimatedSprite

<DodgeMob>:

    neutral_groups: ('mobs',)

    AnimatedSprite:
        id: sprite
        pos: self.parent.pos
        sprite_map: 'dodge_assets/art/enemy.atlas'
        animations: ['walking', 'flying', 'swimming']
        animation: choice(['walking', 'flying', 'swimming'])
        scale_hint: .75
        animation_speed: 3
        autoplay: True
